spring:
  application:
    name: "reactive"
  threads.virtual.enabled: true
  datasource:
    url: "jdbc:postgresql://${DB_IP:localhost}:5432/postgres"
    username: "postgres"
    password: "pass"
    driverClassName: "org.postgresql.Driver"
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"

adapter:
  restconsumer:
    timeout: 5000
    url: "http://${LATENCY_IP:localhost}:8080"

