spring:
  application:
    name: "reactive"

adapter:
  restconsumer:
    timeout: 5000
    url: "http://${LATENCY_IP:localhost}:8080"

database:
  database: "postgres"
  schema: "public"
  username: "postgres"
  password: "pass"
  host: "${DB_IP:localhost}"
  port: 5432

#logging:
#  level:
#    io.r2dbc.postgresql.QUERY: DEBUG